Update pr-checks.yml

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -31,12 +31,12 @@ jobs:
       - name: reads the branch name
         run: echo "Branch:${{ github.head_ref }}"
 
-        if [[ "$branch" =~ ^feature\/.+ ]] || [[ "$branch" =~ ^fix\/.+ ]] || [[ "$branch" =~ ^docs\/.+ ]]; then
-              echo "Branch name is valid."
-            else
-              echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
-              exit 1
-            fi
+         if [[ "$branch" =~ ^feature\/.+ ]] || [[ "$branch" =~ ^fix\/.+ ]] || [[ "$branch" =~ ^docs\/.+ ]]; then
+               echo "Branch name is valid."
+             else
+               echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
+               exit 1
+             fi
  
   pr-body-check:
     runs-on: ubuntu-latest
