updates pr check

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -25,26 +25,28 @@ jobs:
               echo "File is within limits"
             fi
           done
+
   branch-name-check:
     runs-on: ubuntu-latest
     steps:
       - name: reads the branch name
-        run: echo "Branch:${{ github.head_ref }}"
+        run: |
+          echo "Branch:${{ github.head_ref }}"
 
-         if [[ "$branch" =~ ^feature\/.+ ]] || [[ "$branch" =~ ^fix\/.+ ]] || [[ "$branch" =~ ^docs\/.+ ]]; then
-               echo "Branch name is valid."
-             else
-               echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
-               exit 1
-             fi
- 
+          if [[ "${{ github.head_ref }}" =~ ^feature\/.+ ]] || [[ "${{ github.head_ref }}" =~ ^fix\/.+ ]] || [[ "${{ github.head_ref }}" =~ ^docs\/.+ ]]; then
+            echo "Branch name is valid."
+          else
+            echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
+            exit 1
+          fi
+
   pr-body-check:
     runs-on: ubuntu-latest
     steps:
       - name: pr body
         run: |
-          echo "Pr-Body:${{ github.event.pull_request.body }}"
-
+          body="${{ github.event.pull_request.body }}"
+          echo "Pr-Body:$body"
 
           if [ -z "$body" ] || [ "$body" = "null" ]; then
             echo "::warning::PR description is empty. Add context for reviewers."
